Repository meilisearch/firestore-meilisearch, pull requests merged in 2022-09, with the labels that each got.

#102 Change description of displayName to be less than 40 chars
  extension.yaml
Labels: skip-changelog

#111 Convert Meilisearch API key param to secret type
  extension.yaml
Labels: enhancement

#107 Update README to reference Meilisearch cloud
  PREINSTALL.md
  README.md
Labels: documentation

#110 Validate document id formating
  functions/__tests__/functions.test.ts
  functions/lib/index.js
  functions/lib/validate.js
  functions/src/index.ts
  functions/src/logs.ts
  functions/src/validate.ts
  functions/yarn.lock
Labels: bug

#115 Add explaination on tasks login in the post install file
  POSTINSTALL.md
Labels: documentation, skip-changelog

#116 Fix issue where deleting fields in documents are not updated in Meiliseaech
  functions/__tests__/functions.test.ts
  functions/src/index.ts
Labels: bug

#117 Update js-docs with accurate information
  functions/lib/index.js
  functions/lib/logs.js
  functions/lib/validate.js
  functions/src/logs.ts
  functions/src/validate.ts
Labels: skip-changelog

#119 Update outdated build files
  functions/lib/index.js
Labels: skip-changelog
